site_name: GARP docs
site_description: Documentation for the Game Resolution Protocol
theme: readthedocs
nav:
    - 'index.md'
    - 'garp.md'
    - 'garp_v014.md'
    - 'garp_v015.md'
    - 'garp_v020.md'
    - 'garp_v030.md'

